### ISSUE TITLE
gtk+ 3.12 required, while ubuntu LTS has only 3.10

### ISSUE THREAD

**Issue by pawnhearts** [obozrenie/obozrenie#2]
gtk+ 3.12 required, while ubuntu LTS has only 3.10
I suppose .ui file from glade should be saved in older format
    self.builder.add_from_file(GTK_UI_FILE)
gi._glib.GError: assets/obozrenie/ui/obozrenie_gtk.ui: required gtk+ version 3.12, current version is 3.10

If I change 23 line in .ui file to <requires lib="gtk+" version="3.10"/>
I get
gi._glib.GError: Failed to open file 'assets/pixmaps/obozrenie/flags/.svg': No such file or directory
error

**Comment by vorot93** [comment]
@pawnhearts Спасибо за сообщение. 92e11d049f846686f408662f53614d9b852452a9 снизил минимальную версию до 3.10. Можно полный лог второй ошибки? Похоже на кривизну ранних версий PGI.

**Comment by pawnhearts** [comment]
(gtk.py:9826): Gtk-WARNING **: Unknown property: GtkGrid.margin-start

(gtk.py:9826): Gtk-WARNING **: Unknown property: GtkGrid.margin-end

(gtk.py:9826): Gtk-WARNING **: Unknown property: GtkEntry.max-width-chars

(gtk.py:9826): Gtk-WARNING **: Unknown property: GtkScrolledWindow.margin-end

(gtk.py:9826): Gtk-WARNING **: Unknown property: GtkGrid.margin-start

(gtk.py:9826): Gtk-WARNING **: Unknown property: GtkGrid.margin-end
Core/Core: GeoIP data file /usr/share/GeoIP/GeoIP.dat opened successfully.
Traceback (most recent call last):
  File "/home/ph/Downloads/obozrenie/obozrenie/gtk_helpers.py", line 32, in get_icon_dict
    icon_dict[entry] = GdkPixbuf.Pixbuf.new_from_file_at_size(os.path.join(icon_dir, entry.lower() + "." + icon_format), width, height)
gi._glib.GError: Failed to open file 'assets/pixmaps/obozrenie/flags/.svg': No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ph/Downloads/obozrenie/obozrenie/gtk.py", line 509, in <module>
    app = App(core.Core, core.Settings)
  File "/home/ph/Downloads/obozrenie/obozrenie/gtk.py", line 456, in __init__
    self.guiactions = GUIActions(self, self.builder, self.core)
  File "/home/ph/Downloads/obozrenie/obozrenie/gtk.py", line 138, in **init**
    self.flag_icons = gtk_helpers.get_icon_dict(country_db, 'flag', 'svg', ICON_FLAGS_DIR, 24, 18)
  File "/home/ph/Downloads/obozrenie/obozrenie/gtk_helpers.py", line 33, in get_icon_dict
    except GLib.Error:
TypeError: catching classes that do not inherit from BaseException is not allowed

**Comment by vorot93** [comment]
@pawnhearts Похоже на баг в PythonGI, т.к. GLib.Error не наследует Exception. Не наша ошибка, но в коде подлатал. Должно работать.

**Comment by pawnhearts** [comment]
Теперь запускается, но ругается на
  File "/home/ph/Downloads/obozrenie/obozrenie/backends/qstat.py", line 79, in stat_master
    qstat_output, _ = subprocess.Popen(qstat_cmd, stdout=subprocess.PIPE).communicate()
  File "/usr/lib/python3.4/subprocess.py", line 848, in **init**
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1446, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'qstat'

Надо где-то зависимости указать, в readme например?

**Comment by vorot93** [comment]
Готово.
